In [33]:
# mount my google drive to this notebook so I can access my files

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
import pandas as pd

In [38]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Stroke_Prediction/healthcare-dataset-stroke-data.csv")


# https://www.kaggle.com/datasets/shashwatwork/dementia-prediction-dataset

In [41]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [42]:
display(df)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [43]:

df = df.dropna()

le = LabelEncoder()


df['gender'] = le.fit_transform(df.gender.values)
df['ever_married'] = le.fit_transform(df.ever_married.values)
df['work_type'] = le.fit_transform(df.work_type.values)
df['Residence_type'] = le.fit_transform(df.Residence_type.values)
df['smoking_status'] = le.fit_transform(df.smoking_status.values)

<ipython-input-43-caf744545047>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = le.fit_transform(df.gender.values)
<ipython-input-43-caf744545047>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ever_married'] = le.fit_transform(df.ever_married.values)
<ipython-input-43-caf744545047>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['work_type'] = le.fit_transform(df.work_type.values)
<ipython-input-43-caf744545047>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Residence_type'] = le.fit_transform(df.Residence_type.values)
<ipython-input-43-caf744545047>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['smoking_status'] = le.fit_transform(df.smoking_status.values)

In [44]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,1,67.0,0,1,1,2,1,228.69,36.6,1,1
2,31112,1,80.0,0,1,1,2,0,105.92,32.5,2,1
3,60182,0,49.0,0,0,1,2,1,171.23,34.4,3,1
4,1665,0,79.0,1,0,1,3,0,174.12,24.0,2,1
5,56669,1,81.0,0,0,1,2,1,186.21,29.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5104,14180,0,13.0,0,0,0,4,0,103.08,18.6,0,0
5106,44873,0,81.0,0,0,1,3,1,125.20,40.0,2,0
5107,19723,0,35.0,0,0,1,3,0,82.99,30.6,2,0
5108,37544,1,51.0,0,0,1,2,0,166.29,25.6,1,0
5109,44679,0,44.0,0,0,1,0,1,85.28,26.2,0,0

In [ ]:
X = df[['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status']]
y = df['stroke']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = .3, random_state = 0)

In [ ]:
X_train

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
4055,1,68.0,0,1,1,2,0,96.14,26.7,2
612,1,48.0,0,0,1,2,0,147.14,22.3,0
4977,0,44.0,0,0,0,2,0,116.95,26.1,2
2330,1,42.0,0,0,1,2,0,89.22,53.8,0
2962,0,70.0,1,0,1,3,0,154.60,28.5,1
...,...,...,...,...,...,...,...,...,...,...
5057,0,49.0,0,0,1,0,1,69.92,47.6,2
3421,0,51.0,0,0,1,0,0,85.59,30.5,2
1746,1,24.0,1,0,1,2,0,80.63,28.2,3
2733,1,9.0,0,0,0,4,1,142.68,24.4,0
2865,1,58.0,0,0,1,2,1,69.24,27.6,2

In [26]:
from xgboost import XGBRegressor,XGBClassifier
from sklearn.metrics import mean_squared_error

model = XGBClassifier(learning_rate=0.1, max_depth = 3, alpha = 0.1)

model.fit(X_train, y_train)
yhat = model.predict(X_test)

mse = mean_squared_error(y_test, yhat)
print("Mean Squared Error:", mse)

accuracy = accuracy_score(y_test, yhat)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Mean Squared Error: 0.038696537678207736
Accuracy: 96.13%

In [ ]:
import tensorflow as tf
from sklearn.metrics import mean_squared_error, accuracy_score

# define the model architecture
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(12, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='softmax')
])

# compile the model with MSE as the loss function and accuracy as a metric
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

# fit the model to the training data
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

# make predictions on the training data
y_pred = model.predict(X_train)

# calculate the mean squared error and accuracy on the training data
mse = mean_squared_error(y_train, y_pred)
accuracy = accuracy_score(y_train, y_pred.round())
print("Mean Squared Error:", mse)
print("Accuracy:", accuracy)

Epoch 1/100
86/86 [==============================] - 2s 9ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 2/100
86/86 [==============================] - 0s 5ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 3/100
86/86 [==============================] - 1s 7ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 4/100
86/86 [==============================] - 1s 8ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 5/100
86/86 [==============================] - 0s 5ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 6/100
86/86 [==============================] - 0s 6ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 7/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 8/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 9/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 10/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 11/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 12/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 13/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 14/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 15/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 16/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 17/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 18/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 19/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 20/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 21/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 22/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 23/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 24/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 25/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 26/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 27/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 28/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 29/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 30/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 31/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 32/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 33/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 34/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 35/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 36/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 37/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 38/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 39/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 40/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 41/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 42/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 43/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 44/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 45/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 46/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 47/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 48/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 49/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 50/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 51/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 52/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 53/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 54/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 55/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 56/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 57/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 58/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 59/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 60/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 61/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 62/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 63/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 64/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 65/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 66/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 67/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 68/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 69/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 70/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 71/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 72/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 73/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 74/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 75/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 76/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 77/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 78/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 79/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 80/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 81/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 82/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 83/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 84/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 85/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 86/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 87/100
86/86 [==============================] - 0s 2ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 88/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 89/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 90/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 91/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 92/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 93/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 94/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 95/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 96/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 97/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 98/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 99/100
86/86 [==============================] - 0s 3ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
Epoch 100/100
86/86 [==============================] - 0s 4ms/step - loss: 0.9567 - accuracy: 0.0433 - val_loss: 0.9491 - val_accuracy: 0.0509
108/108 [==============================] - 0s 1ms/step
Mean Squared Error: 0.9551803286472528
Accuracy: 0.044819557625145515